-- 向上 / ascend — run this once in the Supabase SQL editor for project chyueowpeovvlwmkfawp.
-- Mirrors the shape of todo_content: one row per track, steps held as JSONB.

create table if not exists public.growth_content (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  icon        text        not null default 'sparkles',
  steps       jsonb       not null default '[]'::jsonb,
  position    integer     not null default 0,
  updated_at  timestamptz not null default now()
);

create index if not exists growth_content_position_idx
  on public.growth_content (position);

-- The app authenticates at the Next.js middleware layer and talks to Supabase
-- with the anon key, so the table is open to anon the same way todo_content is.
-- If todo_content has RLS *disabled*, run this instead and skip the policy below:
--   alter table public.growth_content disable row level security;
alter table public.growth_content enable row level security;

drop policy if exists growth_content_anon_all on public.growth_content;
create policy growth_content_anon_all
  on public.growth_content
  for all
  to anon
  using (true)
  with check (true);

-- Starter tracks. Steps are placeholders — edit them in the UI.
insert into public.growth_content (name, icon, steps, position) values
  ('diet', 'utensils', '[
    {"id":"d1","title":"cut liquid calories","note":"no soda, no juice, black coffee","status":"done"},
    {"id":"d2","title":"protein at every meal","note":"~1g per lb bodyweight","status":"active"},
    {"id":"d3","title":"cook 5 nights a week","note":"","status":"todo"},
    {"id":"d4","title":"dial in a maintenance baseline","note":"","status":"todo"}
  ]'::jsonb, 0),

  ('skincare', 'droplets', '[
    {"id":"s1","title":"cleanser + spf, every morning","note":"the whole routine until it is automatic","status":"done"},
    {"id":"s2","title":"add a nightly moisturizer","note":"","status":"active"},
    {"id":"s3","title":"introduce retinol, 2x a week","note":"ramp slowly","status":"todo"},
    {"id":"s4","title":"targeted serum","note":"only once the base routine is boring","status":"todo"}
  ]'::jsonb, 1),

  ('weight', 'scale', '[
    {"id":"w1","title":"weigh in daily, same time","note":"trend line, not the number","status":"done"},
    {"id":"w2","title":"first cut phase","note":"","status":"active"},
    {"id":"w3","title":"hold the new weight 8 weeks","note":"","status":"todo"},
    {"id":"w4","title":"lean bulk","note":"","status":"todo"}
  ]'::jsonb, 2),

  ('reading', 'book', '[
    {"id":"r1","title":"10 pages before bed","note":"phone in another room","status":"active"},
    {"id":"r2","title":"finish one book a month","note":"","status":"todo"},
    {"id":"r3","title":"keep notes on what stuck","note":"","status":"todo"}
  ]'::jsonb, 3),

  ('gym', 'dumbbell', '[
    {"id":"g1","title":"show up 3x a week","note":"consistency before intensity","status":"done"},
    {"id":"g2","title":"learn the big lifts with light weight","note":"squat, bench, deadlift, row","status":"done"},
    {"id":"g3","title":"progressive overload, logged","note":"add weight or reps every session","status":"active"},
    {"id":"g4","title":"push/pull/legs, 5x a week","note":"","status":"todo"},
    {"id":"g5","title":"1/2/3/4 plates","note":"","status":"todo"}
  ]'::jsonb, 4)
on conflict do nothing;
